### ISSUE TITLE
fail to PR for new pkg

### ISSUE THREAD

**Issue by aumpierre-unb** [gnu-octave/packages#176]
Hi, I'm failing to PR a new pkg proposal:

Run yamllint --format standard -c ./assets/ci/yamllint.yaml packages
packages/mccabe-thiele.yaml
1:4       error    wrong new line character: expected \n  (new-lines)

However no explicit, it seems to me that the problem is in line 1 column 4, what's just after the introductory "---":

\---
layout: "package"
permalink: "mccabe-thiele/"

What's wrong? Any tips?

**Comment by siko1056** [comment]
I think we discussed the problem in #175 . Closing this item, unless there is anything left unclear.
